
// Generated by Cadence Genus(TM) Synthesis Solution 22.15-s086_1
// Generated on: Jul 30 2025 19:07:46 -03 (Jul 30 2025 22:07:46 UTC)

// Verification Directory fv/alu_register_4bit 

module alu_register_4bit(clk, reset, data_in, alu_op, load, data_out,
     zero_flag);
  input clk, reset, load;
  input [3:0] data_in;
  input [1:0] alu_op;
  output [3:0] data_out;
  output zero_flag;
  wire clk, reset, load;
  wire [3:0] data_in;
  wire [1:0] alu_op;
  wire [3:0] data_out;
  wire zero_flag;
  wire n_0, n_1, n_2, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27;
  DFFRHQX1 \data_out_reg[2] (.RN (reset), .CK (clk), .D (n_27), .Q
       (data_out[2]));
  NAND2X1 g601__2398(.A (n_23), .B (n_25), .Y (n_27));
  DFFRHQX1 \data_out_reg[3] (.RN (reset), .CK (clk), .D (n_26), .Q
       (data_out[3]));
  DFFRHQX1 \data_out_reg[0] (.RN (reset), .CK (clk), .D (n_24), .Q
       (data_out[0]));
  OAI221X1 g600__5107(.A0 (n_21), .A1 (n_13), .B0 (n_14), .B1 (n_12),
       .C0 (n_9), .Y (n_26));
  AOI221X1 g603__6260(.A0 (data_out[2]), .A1 (n_16), .B0 (n_17), .B1
       (n_8), .C0 (n_20), .Y (n_25));
  DFFRHQX1 \data_out_reg[1] (.RN (reset), .CK (clk), .D (n_22), .Q
       (data_out[1]));
  OAI211X1 g604__4319(.A0 (data_in[0]), .A1 (n_15), .B0 (n_2), .C0
       (n_23), .Y (n_24));
  OAI221X1 g609__8428(.A0 (n_18), .A1 (n_21), .B0 (n_0), .B1 (n_1), .C0
       (n_19), .Y (n_22));
  NOR2X1 g608__5526(.A (n_21), .B (n_11), .Y (n_20));
  AOI22X1 g610__6783(.A0 (n_18), .A1 (n_17), .B0 (data_out[1]), .B1
       (n_16), .Y (n_19));
  AND2XL g611__3680(.A (n_14), .B (n_21), .Y (n_15));
  XNOR2X1 g606__1617(.A (data_in[3]), .B (n_10), .Y (n_13));
  XNOR2X1 g607__2802(.A (data_in[3]), .B (n_6), .Y (n_12));
  AOI21X1 g612__1705(.A0 (data_in[2]), .A1 (n_4), .B0 (n_10), .Y
       (n_11));
  AOI22X1 g614__5122(.A0 (data_in[3]), .A1 (n_7), .B0 (data_out[3]),
       .B1 (n_16), .Y (n_9));
  XNOR2X1 g613__8246(.A (data_in[2]), .B (n_5), .Y (n_8));
  NAND2X1 g616__7098(.A (alu_op[0]), .B (n_7), .Y (n_23));
  INVX1 g619(.A (n_17), .Y (n_14));
  NOR2BX1 g618__6131(.AN (data_in[2]), .B (n_5), .Y (n_6));
  AND2XL g617__1881(.A (n_5), .B (n_4), .Y (n_18));
  NOR2X1 g620__5115(.A (data_in[2]), .B (n_4), .Y (n_10));
  NOR3X1 g622__7482(.A (alu_op[0]), .B (alu_op[1]), .C (n_16), .Y
       (n_17));
  NOR4X1 g615__4733(.A (data_out[3]), .B (data_out[0]), .C
       (data_out[1]), .D (data_out[2]), .Y (zero_flag));
  NAND3BXL g621__6161(.AN (alu_op[1]), .B (load), .C (alu_op[0]), .Y
       (n_21));
  NAND2X1 g626__9315(.A (data_out[0]), .B (n_16), .Y (n_2));
  INVX1 g623(.A (n_1), .Y (n_7));
  OR2X1 g627__9945(.A (data_in[0]), .B (data_in[1]), .Y (n_4));
  NAND2X1 g624__2883(.A (load), .B (alu_op[1]), .Y (n_1));
  NAND2X1 g625__2346(.A (data_in[0]), .B (data_in[1]), .Y (n_5));
  INVX1 g629(.A (data_in[1]), .Y (n_0));
  INVX1 g628(.A (load), .Y (n_16));
endmodule

