
// Generated by Cadence Genus(TM) Synthesis Solution 22.15-s086_1
// Generated on: Jul 30 2025 18:17:55 -03 (Jul 30 2025 21:17:55 UTC)

// Verification Directory fv/full_adder 

module full_adder(clk, reset, a, b, cin, sum, cout);
  input clk, reset, a, b, cin;
  output sum, cout;
  wire clk, reset, a, b, cin;
  wire sum, cout;
  wire n_0, n_1, n_2;
  DFFRHQX1 sum_reg(.RN (n_2), .CK (clk), .D (n_1), .Q (sum));
  DFFRHQX1 cout_reg(.RN (n_2), .CK (clk), .D (n_0), .Q (cout));
  ADDFX1 g163__2398(.A (a), .B (b), .CI (cin), .CO (n_0), .S (n_1));
  INVXL g164(.A (reset), .Y (n_2));
endmodule

