
// Generated by Cadence Genus(TM) Synthesis Solution 22.15-s086_1
// Generated on: Jul 30 2025 19:17:45 -03 (Jul 30 2025 22:17:45 UTC)

// Verification Directory fv/register_4bit 

module register_4bit(clk, reset, data_in, data_out);
  input clk, reset;
  input [3:0] data_in;
  output [3:0] data_out;
  wire clk, reset;
  wire [3:0] data_in;
  wire [3:0] data_out;
  wire n_0, n_1, n_2, n_3;
  DFFHQX1 \data_out_reg[3] (.CK (clk), .D (n_3), .Q (data_out[3]));
  DFFHQX1 \data_out_reg[2] (.CK (clk), .D (n_0), .Q (data_out[2]));
  DFFHQX1 \data_out_reg[0] (.CK (clk), .D (n_1), .Q (data_out[0]));
  DFFHQX1 \data_out_reg[1] (.CK (clk), .D (n_2), .Q (data_out[1]));
  NOR2BX1 g7__2398(.AN (data_in[3]), .B (reset), .Y (n_3));
  NOR2BX1 g9__5107(.AN (data_in[1]), .B (reset), .Y (n_2));
  NOR2BX1 g8__6260(.AN (data_in[0]), .B (reset), .Y (n_1));
  NOR2BX1 g10__4319(.AN (data_in[2]), .B (reset), .Y (n_0));
endmodule

